language: python
python:
  - 2.7
  - 3.3
  - 3.4
before_install:
  - sudo apt-get update
  - sudo apt-get install -y openssl build-essential xorg libssl-dev
  - wget http://freefr.dl.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements_dev.txt --use-mirrors
  - pip install coveralls
script: nosetests --with-coverage --cover-package resu
after_success:
  coveralls
